### ISSUE TITLE
Kunna välja datumintervall för grafen

### ISSUE THREAD

**Issue by kweh** [Liebe/AdReportViewer#26]
Pratade precis med Kicki som undrade om hon kunde få statistik per månad för en årsbokning. Kan man sätta ett valbart datumintervall på grafen, tro?

**Comment by Liebe** [comment]
Fixat(-ish)! Tror det funkar hyfsat, har några buggar som inte behöver nämnas vid namn. Upplys gärna om ni stöter på något konstigt med den dock.
